# Generated by Django 5.1.2 on 2024-11-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_document_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
