# Generated by Django 5.1.2 on 2024-11-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_document_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
