# Generated by Django 5.1.2 on 2024-11-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_document_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
